version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'pnpm'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10
